language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "node"
  - "lts/*"
notifications:
  email:
    - xkaitian@gmail.com
before_install:
  - npm install -g npm@latest
  - npm i
before_script:
  - npm prune
